name: Auto

on:
  #schedule:
   # - cron: '30 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.7

      - name: requirements
        run : pip3 install -r requirements.txt
      
      - name: Setting
        run: |
         if [ '${{ secrets.cookie }}' != '' ]; then sed -i "s/^cookie: '*${{ secrets.cookie }}'/" ./config.yml; fi
       
      - name: Auto
        run: |
          python3 auto_comment_plus.py
