name: Auto_comment

on:
  #schedule:
   # - cron: '30 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3

      - name: requirements
        run : pip3 install -r requirements.txt

      - name: Setting
        run: |
          sed -i "s/''/'${{ secrets.COOKIE }}'/" ./config.yml
          
      - name: Auto
        run: |
          python3 auto_comment_plus.py
